### PR TITLE
fix(logging) encode try-list as json and no longer use new-line

### LINKED ISSUE #52: Do not write multi-line error logs entries
We see entries like this

```
2018/08/02 19:23:46 [error] 2669#0: *169201 [lua] balancer.lua:783: execute(): [dns] dns server error: 3 name error. Tried: (short)dne:(na) - cache-miss
dne.service.kong-aws-us-west-1:1 - cache-miss/scheduled/querying/dns server error: 3 name error
dne.node.kong-aws-us-west-1:1 - cache-miss/scheduled/querying/dns server error: 3 name error
dne:1 - cache-miss/scheduled/querying/dns server error: 3 name error
dne.service.kong-aws-us-west-1:5 - cache-miss/scheduled/querying/dns server error: 3 name error
dne.node.kong-aws-us-west-1:5 - cache-miss/scheduled/querying/dns client error: 101 empty record received
dne:5 - cache-miss/scheduled/querying/dns server error: 3 name error
dne.service.kong-aws-us-west-1:33 - cache-miss/scheduled/querying/dns server error: 3 name error
dne.node.kong-aws-us-west-1:33 - cache-miss/scheduled/querying/dns client error: 101 empty record received
dne:33 - cache-miss/scheduled/querying/dns server error: 3 name error
, client: 98.173.7.34, server: kong, request: "GET / HTTP/1.1", host: "poprocks.kong-cloud.com"
```

This is impossible to parse correct. It would be great if the `__tostring` metamethod didn't separate these by newline: https://github.com/Kong/lua-resty-dns-client/blob/13c7039884c1af9772ba1d761a417aee60447ee4/src/resty/dns/client.lua#L320

### PR DESCRIPTION
**Pull request by Tieske**
New-line characters in the logging are impossible to parse
correctly so should be prevented.

fixes #52

### CODE REVIEW

File: src/resty/dns/client.lua [hunk 1]
```diff
@@ -318,7 +318,8 @@ local try_list_mt = {
       end
       l[i]="\n"
     end
-    return table_concat(l)
+    -- concatenate result and encode as json array
+    return '[ "' .. table_concat(l, "", 1, i-1):gsub('"',"'"):gsub("\n",'", "') .. '" ]'
```
Comment (hbagdi) [inline src/resty/dns/client.lua]: Encoding this as a JSON seems weird no other logs (correct me) are encoded as JSON.

Comment (Tieske) [reply src/resty/dns/client.lua]: @hbagdi I struggled with it. The newline was there to make it easily human readable. I thought about using different separators for the exiting newlines, but the trouble-shooting experience was pretty bad for all of them hence I did the json thing, which adds an intermediate step for troubleshooting (copy-paste in a json formatter), but then delivers a well readable format.

@hishamhm got 2cts?

**Comment by Tieske** [comment]
@hishamhm updated as per comments, removed spaces and dropped the newline. Please have another look.

File: src/resty/dns/client.lua [hunk 2]
```diff
@@ -311,20 +311,21 @@ local try_list_mt = {
   __tostring = function(self)
     local l, i = {}, 0
     for _, entry in ipairs(self) do
+      l[i] = '","'
```
Comment (hishamhm) [inline src/resty/dns/client.lua]: I may be misreading this, but it looks likes this ends up producing a JSON starting with `["","` (except for `#self == 0` where it does `[]`)

An `l[i] = i == 1 and '"' or '","'` should fix this, but it were me, I'd write it like this instead:

```lua
local l = {}
for i, entry in ipairs(self) do
  local m = tostring(entry.msg):gsub('"',"'")
  local qtype = entry.qtype or "(na)"
  local dash = m ~= "" and " - " or ""
  l[i] = entry.qname .. ":" .. qtype  .. dash .. m
end
return "[" .. table_concat(l, ",") .. "]"
```

The assignment of l[i] becomes a single CAT bytecode, so combining this with the final `concat`, it won't produce the dreaded [pyramid of intermediate strings](https://hisham.hm/2018/07/13/lua-string-concatenation-considered-not-harmful/).

Comment (Tieske) [reply src/resty/dns/client.lua]: > I may be misreading this

The first one is inserted at position 0, hence skipped by the final `concat`

Comment (hishamhm) [reply src/resty/dns/client.lua]: ha! eeeeevil :smiling_imp:
