### PR TITLE
fix(balancer) when dns resolution fails for the last host

### LINKED ISSUE #26: Balancer: getPeer fails
See Kong log below
```
2017/11/02 23:30:05 [warn] 19010#0: *28199029 [lua] balancer.lua:297: queryDns(): [ringbalancer] querying dns for xxx.host.name.xxx failed: dns query returned no results, client: 192.168.13.43, server: kong, request: "GET /mrhyde/dataservices/experiments/configuration/v1 HTTP/1.1", host: "gateway.mydomain.com" 
2017/11/02 23:30:05 [warn] 19010#0: *28199029 [lua] balancer.lua:668: redistributeSlots(): [ringbalancer] redistributed slots, size=100, dropped=100, assigned=0, left unassigned=100, client: 192.168.13.43, server: kong, request: "GET /mrhyde/dataservices/experiments/configuration/v1 HTTP/1.1", host: "gateway.mydomain.com" 
2017/11/02 23:30:05 [error] 19010#0: *28199029 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/dns/balancer.lua:539: attempt to index field 'address' (a nil value) 
stack traceback: 
coroutine 0: 
/usr/local/share/lua/5.1/resty/dns/balancer.lua: in function 'getPeer' 
/usr/local/share/lua/5.1/kong/core/balancer.lua:281: in function 'balancer_execute' 
/usr/local/share/lua/5.1/kong/core/handler.lua:126: in function 'before' 
/usr/local/share/lua/5.1/kong.lua:292: in function 'access' 
access_by_lua(nginx-kong.conf:96):2: in function <access_by_lua(nginx-kong.conf:96):1>, client: 192.168.13.43, server: kong, request: "GET /mrhyde/dataservices/experiments/configuration/v1 HTTP/1.1", host: "gateway.mydomain.com" 
```

The error seems to be an edge case. The DNS record fails to resolve: see `dns query returned no results` in the log, hence the ring balancer releases all its slots;
```
[ringbalancer] redistributed slots, size=100, dropped=100, assigned=0, left unassigned=100
```
When, in this state a `getPeer` is requested, it will check assignments and return a functional error "No peers are available". The problem here occurs because the "redistribution" happens in this case after that check, inside `getPeer`. Due to this it tries to access an address that is no longer available.

It does not matter for the final result, as it would have failed to proxy anyway, but it should have been a proper "No peers are available" instead of trowing an error which results in a 500.

As for the dns results; the "dns query returned no results" error occurs when the server replies, but with an empty record. See https://github.com/Kong/lua-resty-dns-client/blob/0.4.x/src/resty/dns/client.lua#L706-L725

### PR DESCRIPTION
**Pull request by Tieske**
fixes #26

### CODE REVIEW

File: src/resty/dns/balancer.lua [hunk 1]
```diff
@@ -856,7 +856,11 @@ function objBalancer:getPeer(hashValue, retryCount, cacheOnly)
     if ip then
       return ip, port, hostname
     elseif port == ERR_SLOT_REASSIGNED then
-      -- we just need to retry the same slot, no change for 'pointer'
+      -- we just need to retry the same slot, no change for 'pointer', just
+      -- in case of dns updates, we need to check our weight again.
+      if self.weight == 0 then
+        return nil, ERR_NO_PEERS_AVAILABLE
+      end
```
Comment (hishamhm) [inline src/resty/dns/balancer.lua]: Is this part necessary? I'm asking this more to gauge my own understanding of the code. From my reading recursing in that situation would fall into "No peers available" already.

On Friday I had a patch written that only did the change on line 569, but I didn't submit a PR because I didn't have a test. I just took the test you added above and ran it with the line 569 change only, and the test passes, so either this is not necessary or the test isn't catching the situation you are testing for here.

Comment (Tieske) [reply src/resty/dns/balancer.lua]: yes it is necessary. The pointer is not adjusted, so in the next iteration, at line `854` we get the same slot. And at line `855` we access `slot.address.host`, but `slot.address == nil` hence an error occurs.

This branch with those lines commented out:

```
[ RUN      ] spec/balancer_spec.lua @ 1677: Loadbalancer slot manipulation renewed DNS A record; last host fails DNS resolution
2017/11/06 23:35:40 [warn] 6078#0: *2 [lua] balancer.lua:320: queryDns(): [ringbalancer] querying dns for really.does.not.exist.mashape.com failed: dns server error: 3 name error, context: ngx.timer
2017/11/06 23:35:40 [warn] 6078#0: *2 [lua] balancer.lua:698: redistributeSlots(): [ringbalancer] redistributed slots, size=1000, dropped=1000, assigned=0, left unassigned=1000, context: ngx.timer
./src/resty/dns/balancer.lua:855: attempt to index field 'address' (a nil value)

stack traceback:
	./src/resty/dns/balancer.lua:855: in function 'getPeer'
	spec/balancer_spec.lua:1701: in function <spec/balancer_spec.lua:1677>

[  ERROR   ] spec/balancer_spec.lua @ 1677: Loadbalancer slot manipulation renewed DNS A record; last host fails DNS resolution (319.13 ms)
```

Comment (Tieske) [reply src/resty/dns/balancer.lua]: Did your patch do anything else? I can't see how it would work without those lines as well?

Comment (hishamhm) [reply src/resty/dns/balancer.lua]: Ah, I wrote the patch against the `0.4.x` branch, which was where the problem was first reported. In that branch the first change alone makes the test pass. Do you want me to submit the PR to that branch?

Comment (Tieske) [reply src/resty/dns/balancer.lua]: No, it just changes the error message, the situation itself can't be resolved. So no need to back port to the old branch for Kong 0.10.x imo

Comment (hishamhm) [reply src/resty/dns/balancer.lua]: well, it changes a crash into a proper error message so it's an improvement at least :) since I had the branch laying around I submitted the PR anyway.
